openapi: 3.0.0
info:
  title: Customer Management API
  description: API para la gestión de clientes del sistema bancario XYZ
  version: 1.0.0
  contact:
    name: JavaPowerGirls Team
    email: support@bankxyz.com

servers:
  - url: http://localhost:8081
    description: Servidor de desarrollo

paths:
  /api/v1/clients:
    get:
      summary: Listar todos los clientes
      description: Obtiene una lista de todos los clientes registrados en el sistema
      operationId: getAllClients
      tags:
        - Clientes
      responses:
        '200':
          description: Lista de clientes obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '500':
          description: Error interno del servidor

    post:
      summary: Crear un nuevo cliente
      description: Registra un nuevo cliente en el sistema bancario
      operationId: createClient
      tags:
        - Clientes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        '201':
          description: Cliente creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/clients/{id}:
    get:
      summary: Obtener cliente por ID
      description: Obtiene los detalles de un cliente específico por su ID
      operationId: getClientById
      tags:
        - Clientes
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Actualizar datos de un cliente
      description: Actualiza la información de un cliente existente
      operationId: updateClient
      tags:
        - Clientes
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        '200':
          description: Cliente actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cliente no encontrado

    delete:
      summary: Eliminar un cliente
      description: Elimina un cliente del sistema si no tiene cuentas bancarias activas
      operationId: deleteClient
      tags:
        - Clientes
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Cliente eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Client with given id successfully deleted"
        '400':
          description: No se puede eliminar cliente con cuentas activas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cliente no encontrado

components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único del cliente
          example: 1
        firstName:
          type: string
          description: Nombre del cliente
          example: "Juan"
        lastName:
          type: string
          description: Apellido del cliente
          example: "Pérez"
        dni:
          type: string
          description: DNI único del cliente
          example: "12345678A"
        email:
          type: string
          format: email
          description: Correo electrónico del cliente
          example: "juan.perez@email.com"
      required:
        - id
        - firstName
        - lastName
        - dni
        - email

    ClientRequest:
      type: object
      properties:
        firstName:
          type: string
          description: Nombre del cliente
          example: "Juan"
        lastName:
          type: string
          description: Apellido del cliente
          example: "Pérez"
        dni:
          type: string
          description: DNI único del cliente
          example: "12345678A"
        email:
          type: string
          format: email
          description: Correo electrónico del cliente
          example: "juan.perez@email.com"
      required:
        - firstName
        - lastName
        - dni
        - email

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp del error
        status:
          type: integer
          description: Código de estado HTTP
        error:
          type: string
          description: Tipo de error
        message:
          type: string
          description: Mensaje descriptivo del error
        path:
          type: string
          description: Ruta donde ocurrió el error
